services:
  web:
    build: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    
  ngrok:
    image: ngrok/ngrok:latest
    command: "http --url=darling-lenient-meerkat.ngrok-free.app web:5000"
    depends_on:
      - web
    environment:
      - NGROK_AUTHTOKEN=30yRwwHlqsy0D3sfOH7h7qLxw2Q_ZLbbF5z9GGyfw4UPAEXV
    ports:
      - "4040:4040"
